#:schema node_modules/wrangler/config-schema.json
name = "fresko"
main = ".open-next/worker.js"
compatibility_date = "2025-05-26"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "fresko-db"
database_id = "local"
